// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: merchants.sql

package database

import (
	"context"
)

const getMerchantBySlug = `-- name: GetMerchantBySlug :one
SELECT id, slug, display_name, merchant_password_hash, customer_password_hash, created_at, updated_at
FROM merchants
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetMerchantBySlug(ctx context.Context, slug string) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantBySlug, slug)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.MerchantPasswordHash,
		&i.CustomerPasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
