// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Merchant struct {
	ID                   pgtype.UUID        `json:"id"`
	Slug                 string             `json:"slug"`
	DisplayName          string             `json:"display_name"`
	MerchantPasswordHash string             `json:"merchant_password_hash"`
	CustomerPasswordHash string             `json:"customer_password_hash"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Pet struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	Name        string             `json:"name"`
	Species     string             `json:"species"`
	AgeYears    int32              `json:"age_years"`
	Description string             `json:"description"`
	ImagePath   string             `json:"image_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	SoldAt      pgtype.Timestamptz `json:"sold_at"`
	RemovedAt   pgtype.Timestamptz `json:"removed_at"`
}

type Sale struct {
	ID             pgtype.UUID        `json:"id"`
	MerchantID     pgtype.UUID        `json:"merchant_id"`
	PetID          pgtype.UUID        `json:"pet_id"`
	SoldAt         pgtype.Timestamptz `json:"sold_at"`
	PurchaseMethod string             `json:"purchase_method"`
}
