// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: pets.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPet = `-- name: CreatePet :one
INSERT INTO pets (
    merchant_id,
    name,
    species,
    age_years,
    description,
    image_path
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, merchant_id, name, species, age_years, description, image_path, created_at, sold_at, removed_at
`

type CreatePetParams struct {
	MerchantID  pgtype.UUID `json:"merchant_id"`
	Name        string      `json:"name"`
	Species     string      `json:"species"`
	AgeYears    int32       `json:"age_years"`
	Description string      `json:"description"`
	ImagePath   string      `json:"image_path"`
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error) {
	row := q.db.QueryRow(ctx, createPet,
		arg.MerchantID,
		arg.Name,
		arg.Species,
		arg.AgeYears,
		arg.Description,
		arg.ImagePath,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Species,
		&i.AgeYears,
		&i.Description,
		&i.ImagePath,
		&i.CreatedAt,
		&i.SoldAt,
		&i.RemovedAt,
	)
	return i, err
}

const findUnavailablePets = `-- name: FindUnavailablePets :many
SELECT id, name, sold_at, removed_at
FROM pets
WHERE merchant_id = $1
  AND id = ANY($2::uuid[])
  AND (sold_at IS NOT NULL OR removed_at IS NOT NULL)
`

type FindUnavailablePetsParams struct {
	MerchantID pgtype.UUID   `json:"merchant_id"`
	Column2    []pgtype.UUID `json:"column_2"`
}

type FindUnavailablePetsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	SoldAt    pgtype.Timestamptz `json:"sold_at"`
	RemovedAt pgtype.Timestamptz `json:"removed_at"`
}

func (q *Queries) FindUnavailablePets(ctx context.Context, arg FindUnavailablePetsParams) ([]FindUnavailablePetsRow, error) {
	rows, err := q.db.Query(ctx, findUnavailablePets, arg.MerchantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUnavailablePetsRow
	for rows.Next() {
		var i FindUnavailablePetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SoldAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPetsForUpdate = `-- name: GetPetsForUpdate :many
SELECT id, merchant_id, name, species, age_years, description, image_path, created_at, sold_at, removed_at
FROM pets
WHERE merchant_id = $1
  AND id = ANY($2::uuid[])
  AND sold_at IS NULL
  AND removed_at IS NULL
FOR UPDATE
`

type GetPetsForUpdateParams struct {
	MerchantID pgtype.UUID   `json:"merchant_id"`
	Column2    []pgtype.UUID `json:"column_2"`
}

func (q *Queries) GetPetsForUpdate(ctx context.Context, arg GetPetsForUpdateParams) ([]Pet, error) {
	rows, err := q.db.Query(ctx, getPetsForUpdate, arg.MerchantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pet
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Species,
			&i.AgeYears,
			&i.Description,
			&i.ImagePath,
			&i.CreatedAt,
			&i.SoldAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailablePetsByMerchant = `-- name: ListAvailablePetsByMerchant :many
SELECT id, merchant_id, name, species, age_years, description, image_path, created_at, sold_at, removed_at
FROM pets
WHERE merchant_id = $1
  AND sold_at IS NULL
  AND removed_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListAvailablePetsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Pet, error) {
	rows, err := q.db.Query(ctx, listAvailablePetsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pet
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Species,
			&i.AgeYears,
			&i.Description,
			&i.ImagePath,
			&i.CreatedAt,
			&i.SoldAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantUnsoldPets = `-- name: ListMerchantUnsoldPets :many
SELECT id, merchant_id, name, species, age_years, description, image_path, created_at, sold_at, removed_at
FROM pets
WHERE merchant_id = $1
  AND sold_at IS NULL
  AND removed_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListMerchantUnsoldPets(ctx context.Context, merchantID pgtype.UUID) ([]Pet, error) {
	rows, err := q.db.Query(ctx, listMerchantUnsoldPets, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pet
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Species,
			&i.AgeYears,
			&i.Description,
			&i.ImagePath,
			&i.CreatedAt,
			&i.SoldAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPetRemoved = `-- name: MarkPetRemoved :one
UPDATE pets
SET removed_at = NOW()
WHERE id = $1
  AND merchant_id = $2
  AND sold_at IS NULL
  AND removed_at IS NULL
RETURNING id, merchant_id, name, species, age_years, description, image_path, created_at, sold_at, removed_at
`

type MarkPetRemovedParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) MarkPetRemoved(ctx context.Context, arg MarkPetRemovedParams) (Pet, error) {
	row := q.db.QueryRow(ctx, markPetRemoved, arg.ID, arg.MerchantID)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Species,
		&i.AgeYears,
		&i.Description,
		&i.ImagePath,
		&i.CreatedAt,
		&i.SoldAt,
		&i.RemovedAt,
	)
	return i, err
}

const markPetSold = `-- name: MarkPetSold :one
UPDATE pets
SET sold_at = $3
WHERE id = $1
  AND merchant_id = $2
  AND sold_at IS NULL
  AND removed_at IS NULL
RETURNING id, merchant_id, name, species, age_years, description, image_path, created_at, sold_at, removed_at
`

type MarkPetSoldParams struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	SoldAt     pgtype.Timestamptz `json:"sold_at"`
}

func (q *Queries) MarkPetSold(ctx context.Context, arg MarkPetSoldParams) (Pet, error) {
	row := q.db.QueryRow(ctx, markPetSold, arg.ID, arg.MerchantID, arg.SoldAt)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Species,
		&i.AgeYears,
		&i.Description,
		&i.ImagePath,
		&i.CreatedAt,
		&i.SoldAt,
		&i.RemovedAt,
	)
	return i, err
}
