// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error)
	FindUnavailablePets(ctx context.Context, arg FindUnavailablePetsParams) ([]FindUnavailablePetsRow, error)
	GetMerchantBySlug(ctx context.Context, slug string) (Merchant, error)
	GetPetsForUpdate(ctx context.Context, arg GetPetsForUpdateParams) ([]Pet, error)
	InsertSale(ctx context.Context, arg InsertSaleParams) (Sale, error)
	ListAvailablePetsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]Pet, error)
	ListMerchantUnsoldPets(ctx context.Context, merchantID pgtype.UUID) ([]Pet, error)
	ListSalesByMerchantAndRange(ctx context.Context, arg ListSalesByMerchantAndRangeParams) ([]ListSalesByMerchantAndRangeRow, error)
	MarkPetRemoved(ctx context.Context, arg MarkPetRemovedParams) (Pet, error)
	MarkPetSold(ctx context.Context, arg MarkPetSoldParams) (Pet, error)
}

var _ Querier = (*Queries)(nil)
