// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sales.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSale = `-- name: InsertSale :one
INSERT INTO sales (
    merchant_id,
    pet_id,
    sold_at,
    purchase_method
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, merchant_id, pet_id, sold_at, purchase_method
`

type InsertSaleParams struct {
	MerchantID     pgtype.UUID        `json:"merchant_id"`
	PetID          pgtype.UUID        `json:"pet_id"`
	SoldAt         pgtype.Timestamptz `json:"sold_at"`
	PurchaseMethod string             `json:"purchase_method"`
}

func (q *Queries) InsertSale(ctx context.Context, arg InsertSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, insertSale,
		arg.MerchantID,
		arg.PetID,
		arg.SoldAt,
		arg.PurchaseMethod,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PetID,
		&i.SoldAt,
		&i.PurchaseMethod,
	)
	return i, err
}

const listSalesByMerchantAndRange = `-- name: ListSalesByMerchantAndRange :many
SELECT
    s.id AS sale_id,
    s.merchant_id AS sale_merchant_id,
    s.pet_id AS sale_pet_id,
    s.sold_at AS sale_sold_at,
    s.purchase_method AS sale_purchase_method,
    p.id AS pet_id,
    p.merchant_id AS pet_merchant_id,
    p.name AS pet_name,
    p.species AS pet_species,
    p.age_years AS pet_age_years,
    p.description AS pet_description,
    p.image_path AS pet_image_path,
    p.created_at AS pet_created_at,
    p.sold_at AS pet_sold_at,
    p.removed_at AS pet_removed_at
FROM sales s
JOIN pets p ON p.id = s.pet_id
WHERE s.merchant_id = $1
  AND s.sold_at >= $2
  AND s.sold_at <= $3
ORDER BY s.sold_at DESC
`

type ListSalesByMerchantAndRangeParams struct {
	MerchantID pgtype.UUID        `json:"merchant_id"`
	SoldAt     pgtype.Timestamptz `json:"sold_at"`
	SoldAt_2   pgtype.Timestamptz `json:"sold_at_2"`
}

type ListSalesByMerchantAndRangeRow struct {
	SaleID             pgtype.UUID        `json:"sale_id"`
	SaleMerchantID     pgtype.UUID        `json:"sale_merchant_id"`
	SalePetID          pgtype.UUID        `json:"sale_pet_id"`
	SaleSoldAt         pgtype.Timestamptz `json:"sale_sold_at"`
	SalePurchaseMethod string             `json:"sale_purchase_method"`
	PetID              pgtype.UUID        `json:"pet_id"`
	PetMerchantID      pgtype.UUID        `json:"pet_merchant_id"`
	PetName            string             `json:"pet_name"`
	PetSpecies         string             `json:"pet_species"`
	PetAgeYears        int32              `json:"pet_age_years"`
	PetDescription     string             `json:"pet_description"`
	PetImagePath       string             `json:"pet_image_path"`
	PetCreatedAt       pgtype.Timestamptz `json:"pet_created_at"`
	PetSoldAt          pgtype.Timestamptz `json:"pet_sold_at"`
	PetRemovedAt       pgtype.Timestamptz `json:"pet_removed_at"`
}

func (q *Queries) ListSalesByMerchantAndRange(ctx context.Context, arg ListSalesByMerchantAndRangeParams) ([]ListSalesByMerchantAndRangeRow, error) {
	rows, err := q.db.Query(ctx, listSalesByMerchantAndRange, arg.MerchantID, arg.SoldAt, arg.SoldAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesByMerchantAndRangeRow
	for rows.Next() {
		var i ListSalesByMerchantAndRangeRow
		if err := rows.Scan(
			&i.SaleID,
			&i.SaleMerchantID,
			&i.SalePetID,
			&i.SaleSoldAt,
			&i.SalePurchaseMethod,
			&i.PetID,
			&i.PetMerchantID,
			&i.PetName,
			&i.PetSpecies,
			&i.PetAgeYears,
			&i.PetDescription,
			&i.PetImagePath,
			&i.PetCreatedAt,
			&i.PetSoldAt,
			&i.PetRemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
