// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreatePetInput struct {
	Name        string  `json:"name"`
	Species     Species `json:"species"`
	AgeYears    int     `json:"ageYears"`
	Description string  `json:"description"`
	ImagePath   string  `json:"imagePath"`
}

type DateRangeInput struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type Mutation struct {
}

type Pet struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Species     Species    `json:"species"`
	AgeYears    int        `json:"ageYears"`
	Description string     `json:"description"`
	ImagePath   string     `json:"imagePath"`
	CreatedAt   time.Time  `json:"createdAt"`
	SoldAt      *time.Time `json:"soldAt,omitempty"`
	RemovedAt   *time.Time `json:"removedAt,omitempty"`
}

type PurchaseCartInput struct {
	PetIds []string `json:"petIds"`
}

type PurchaseError struct {
	PetID   *string `json:"petId,omitempty"`
	Message string  `json:"message"`
}

type PurchaseResult struct {
	Success       bool             `json:"success"`
	PurchasedPets []*Pet           `json:"purchasedPets"`
	Errors        []*PurchaseError `json:"errors"`
}

type Query struct {
}

type SoldPet struct {
	Pet    *Pet      `json:"pet"`
	SoldAt time.Time `json:"soldAt"`
}

type Species string

const (
	SpeciesCat  Species = "CAT"
	SpeciesDog  Species = "DOG"
	SpeciesFrog Species = "FROG"
)

var AllSpecies = []Species{
	SpeciesCat,
	SpeciesDog,
	SpeciesFrog,
}

func (e Species) IsValid() bool {
	switch e {
	case SpeciesCat, SpeciesDog, SpeciesFrog:
		return true
	}
	return false
}

func (e Species) String() string {
	return string(e)
}

func (e *Species) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Species(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Species", str)
	}
	return nil
}

func (e Species) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
