package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/vektah/gqlparser/v2/gqlerror"

	"github.com/nimble-challenge/petstore/internal/auth"
	"github.com/nimble-challenge/petstore/internal/database"
)

const (
	purchaseMethodDirect = "DIRECT"
	purchaseMethodCart   = "CART"
)

// MerchantCreatePet is the resolver for the merchantCreatePet field.
func (r *mutationResolver) MerchantCreatePet(ctx context.Context, input CreatePetInput) (*Pet, error) {
	principal, err := requireRole(ctx, auth.RoleMerchant)
	if err != nil {
		return nil, err
	}

	if !input.Species.IsValid() {
		return nil, gqlerror.Errorf("invalid species value %q", input.Species)
	}

	if input.AgeYears < 0 {
		return nil, gqlerror.Errorf("ageYears must be non-negative")
	}

	pet, err := r.DB.CreatePet(ctx, database.CreatePetParams{
		MerchantID:  principal.Merchant.ID,
		Name:        strings.TrimSpace(input.Name),
		Species:     input.Species.String(),
		AgeYears:    int32(input.AgeYears),
		Description: strings.TrimSpace(input.Description),
		ImagePath:   strings.TrimSpace(input.ImagePath),
	})
	if err != nil {
		return nil, err
	}

	return mapPet(pet)
}

// MerchantRemovePet is the resolver for the merchantRemovePet field.
func (r *mutationResolver) MerchantRemovePet(ctx context.Context, id string) (bool, error) {
	principal, err := requireRole(ctx, auth.RoleMerchant)
	if err != nil {
		return false, err
	}

	petID, err := uuidToPg(id)
	if err != nil {
		return false, gqlerror.Errorf("invalid pet id")
	}

	_, err = r.DB.MarkPetRemoved(ctx, database.MarkPetRemovedParams{
		ID:         petID,
		MerchantID: principal.Merchant.ID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// CustomerPurchasePet is the resolver for the customerPurchasePet field.
func (r *mutationResolver) CustomerPurchasePet(ctx context.Context, id string) (*PurchaseResult, error) {
	principal, err := requireRole(ctx, auth.RoleCustomer)
	if err != nil {
		return nil, err
	}
	return r.purchasePets(ctx, principal, []string{id}, purchaseMethodDirect)
}

// CustomerPurchaseCart is the resolver for the customerPurchaseCart field.
func (r *mutationResolver) CustomerPurchaseCart(ctx context.Context, input PurchaseCartInput) (*PurchaseResult, error) {
	principal, err := requireRole(ctx, auth.RoleCustomer)
	if err != nil {
		return nil, err
	}
	if len(input.PetIds) == 0 {
		return &PurchaseResult{
			Success: false,
			Errors: []*PurchaseError{
				{
					Message: "cart is empty",
				},
			},
		}, nil
	}

	return r.purchasePets(ctx, principal, input.PetIds, purchaseMethodCart)
}

// MerchantUnsoldPets is the resolver for the merchantUnsoldPets field.
func (r *queryResolver) MerchantUnsoldPets(ctx context.Context) ([]*Pet, error) {
	principal, err := requireRole(ctx, auth.RoleMerchant)
	if err != nil {
		return nil, err
	}

	pets, err := r.DB.ListMerchantUnsoldPets(ctx, principal.Merchant.ID)
	if err != nil {
		return nil, err
	}

	return mapPets(pets)
}

// MerchantSoldPets is the resolver for the merchantSoldPets field.
func (r *queryResolver) MerchantSoldPets(ctx context.Context, rangeArg DateRangeInput) ([]*SoldPet, error) {
	principal, err := requireRole(ctx, auth.RoleMerchant)
	if err != nil {
		return nil, err
	}

	if rangeArg.End.Before(rangeArg.Start) {
		return nil, gqlerror.Errorf("end must be after start")
	}

	rows, err := r.DB.ListSalesByMerchantAndRange(ctx, database.ListSalesByMerchantAndRangeParams{
		MerchantID: principal.Merchant.ID,
		SoldAt: pgtype.Timestamptz{
			Time:  rangeArg.Start,
			Valid: true,
		},
		SoldAt_2: pgtype.Timestamptz{
			Time:  rangeArg.End,
			Valid: true,
		},
	})
	if err != nil {
		return nil, err
	}

	result := make([]*SoldPet, 0, len(rows))
	for _, row := range rows {
		mapped, err := mapSoldPet(row)
		if err != nil {
			return nil, err
		}
		result = append(result, mapped)
	}
	return result, nil
}

// CustomerAvailablePets is the resolver for the customerAvailablePets field.
func (r *queryResolver) CustomerAvailablePets(ctx context.Context) ([]*Pet, error) {
	principal, err := requireRole(ctx, auth.RoleCustomer)
	if err != nil {
		return nil, err
	}

	pets, err := r.DB.ListAvailablePetsByMerchant(ctx, principal.Merchant.ID)
	if err != nil {
		return nil, err
	}

	return mapPets(pets)
}

func (r *mutationResolver) purchasePets(ctx context.Context, principal auth.Principal, ids []string, method string) (*PurchaseResult, error) {
	uniqueIDs := uniqueStrings(ids)
	if len(uniqueIDs) == 0 {
		return &PurchaseResult{
			Success: false,
			Errors: []*PurchaseError{
				{Message: "no pets requested"},
			},
		}, nil
	}

	var pgIDs []pgtype.UUID
	for _, raw := range uniqueIDs {
		converted, err := uuidToPg(raw)
		if err != nil {
			return nil, gqlerror.Errorf("invalid pet id %q", raw)
		}
		pgIDs = append(pgIDs, converted)
	}

	tx, err := r.Pool.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx) // nolint:errcheck

	qtx := r.DB.WithTx(tx)
	lockedPets, err := qtx.GetPetsForUpdate(ctx, database.GetPetsForUpdateParams{
		MerchantID: principal.Merchant.ID,
		Column2:    pgIDs,
	})
	if err != nil {
		return nil, err
	}

	lockedMap := make(map[string]database.Pet, len(lockedPets))
	for _, pet := range lockedPets {
		u, err := uuidFromPg(pet.ID)
		if err != nil {
			return nil, err
		}
		lockedMap[u.String()] = pet
	}

	missingIDs := difference(uniqueIDs, lockedMap)
	errorList, err := r.describeMissingPets(ctx, principal, missingIDs)
	if err != nil {
		return nil, err
	}

	purchased := make([]*Pet, 0, len(lockedPets))
	now := time.Now().UTC()
	soldAt := pgtype.Timestamptz{Time: now, Valid: true}

	for _, pet := range lockedPets {
		sold, err := qtx.MarkPetSold(ctx, database.MarkPetSoldParams{
			ID:         pet.ID,
			MerchantID: pet.MerchantID,
			SoldAt:     soldAt,
		})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				// Someone else purchased in parallel; add to errors later.
				id, convErr := uuidFromPg(pet.ID)
				if convErr != nil {
					return nil, convErr
				}
				errorList = append(errorList, &PurchaseError{
					PetID:   ptr(id.String()),
					Message: fmt.Sprintf("%s is no longer available.", pet.Name),
				})
				continue
			}
			return nil, err
		}

		_, err = qtx.InsertSale(ctx, database.InsertSaleParams{
			MerchantID:     principal.Merchant.ID,
			PetID:          pet.ID,
			SoldAt:         soldAt,
			PurchaseMethod: method,
		})
		if err != nil {
			return nil, err
		}

		mapped, err := mapPet(sold)
		if err != nil {
			return nil, err
		}
		purchased = append(purchased, mapped)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}

	success := len(errorList) == 0
	return &PurchaseResult{
		Success:       success,
		PurchasedPets: purchased,
		Errors:        errorList,
	}, nil
}

func (r *mutationResolver) describeMissingPets(ctx context.Context, principal auth.Principal, missing []string) ([]*PurchaseError, error) {
	if len(missing) == 0 {
		return nil, nil
	}

	var pgIDs []pgtype.UUID
	for _, id := range missing {
		converted, err := uuidToPg(id)
		if err != nil {
			continue
		}
		pgIDs = append(pgIDs, converted)
	}

	rows, err := r.DB.FindUnavailablePets(ctx, database.FindUnavailablePetsParams{
		MerchantID: principal.Merchant.ID,
		Column2:    pgIDs,
	})
	if err != nil {
		return nil, err
	}

	nameByID := make(map[string]string, len(rows))
	for _, row := range rows {
		id, err := uuidFromPg(row.ID)
		if err != nil {
			return nil, err
		}
		nameByID[id.String()] = row.Name
	}

	var errorsList []*PurchaseError
	for _, id := range missing {
		name, ok := nameByID[id]
		message := "pet is not available."
		if ok {
			message = fmt.Sprintf("%s is no longer available.", name)
		}
		errorsList = append(errorsList, &PurchaseError{
			PetID:   ptr(id),
			Message: message,
		})
	}
	return errorsList, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func requireRole(ctx context.Context, expected auth.Role) (auth.Principal, error) {
	principal, ok := auth.PrincipalFromContext(ctx)
	if !ok {
		return auth.Principal{}, gqlerror.Errorf("unauthorized")
	}
	if principal.Role != expected {
		return auth.Principal{}, gqlerror.Errorf("unauthorized")
	}
	return principal, nil
}

func uniqueStrings(values []string) []string {
	set := make(map[string]struct{}, len(values))
	var result []string
	for _, value := range values {
		if _, exists := set[value]; exists {
			continue
		}
		set[value] = struct{}{}
		result = append(result, value)
	}
	return result
}

func difference(ids []string, locked map[string]database.Pet) []string {
	var missing []string
	for _, id := range ids {
		if _, ok := locked[id]; !ok {
			missing = append(missing, id)
		}
	}
	return missing
}

func ptr[T any](value T) *T {
	return &value
}
